### ISSUE TITLE
Search are broken

### ISSUE THREAD

**Issue by villander** [betocantu93/octane-ecommerce#1]
In http://octane-ecommerce.surge.sh

![image](https://user-images.githubusercontent.com/10222774/57053285-6135f900-6c63-11e9-897f-ae2f7afd0542.png)

**Comment by betocantu93** [comment]
thanks for the feedback, I can't reproduce it, though, do you recall how to reproduce it? also, recently I added FastBoot support and deployed to Heroku instead of surge, maybe, in the last deployed version, it works?

its on a free dyno, so, it will load slightly slow if cold start
[FastBoot enabled](https://octane-ecommerce.herokuapp.com/)

**Comment by betocantu93** [comment]
Got the issue, somehow serialization/deserialization of arrays in queryParams get broken if I typed fast in the search box, I just made a deserialization / serialization of arrays with commas... split and join

**Comment by villander** [comment]
thanks @betocantu93 🏆
